# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e8253dd36cde3da4308bcd3c0e1cc91bdfa80eb5437d2830e407ff36a0703f9d1463fed300ee804aa7825bd4213712b45ad18a377d2d9918ccc32258d43c05e

test:
  secret_key_base: bd51921c3fde08efc7745f468bf06af56066b97b60ce424c1cf77d87ac9bfa9f3eb190d6dd9d096e2423e831032ece01fb168ac51ae19cadc71dd661c17e501b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
